### ISSUE TITLE
[Error: Call connectUser or connectAnonymousUser before creating a channel]

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-js#1092] opened 2023-01-30 18:54 UTC
Hello.

My work env:

```
"react-native" : "0.64.3",
"stream-chat": "7.1.0",
"stream-chat-react-native" : "^5.5.0"
```

When creating a channel, I`ve implemented this way.
```
const conversation = client.channel(`messaging`, [uuid], { members: [ `user1`, `user2` ] });
await conversation.create();
```

It normally works fine, but sometimes I see this error.

_`[Error: Call connectUser or connectAnonymousUser before creating a channel]`_

What will be the reason?

Thanks.

**Comment by vanGalilea** [comment] 2023-01-31 09:22
@cleandevcode thanks for reaching out, can you please share the rest of the code? (what happens prior to what you've posted, also client creation etc.). This will help us get to the root cause of this issue.

**Comment by cleandevcode** [comment] 2023-01-31 16:46
Thanks for your message.

- Chat client
```
const client: StreamChat<MeshChatGenerics> = StreamChat.getInstance(streamApiKey);

export {client}
```
- Conversation Create
```
import { client } from './client';

const channelType = `messaging`;
const channelId = `something`;    // uuid comes from Back-end
const channelData = [`user1`, `user2`] //. user Ids come from Back-end

const conversation = client.channel(channelType, channelId, channelData);
await conversation.create();
```


Many thanks.

**Comment by vanGalilea** [comment] 2023-02-07 10:01
Are you calling `connectUser` somewhere in your code? 

When reading the error message, it states that you haven't called it yet `[Error: Call connectUser or connectAnonymousUser before creating a channel]`

This should be the flow in a nutshell:
```
  const userClient = new StreamChat('API_KEY');
  await userClient.connectUser({id: 'USER_NAME'}, 'USER_TOKEN');
  const channel = client.channel('messaging', {
      members: ['USER_NAME', 'SOME_OTHER_USER_NAME'],
  });
  await channel.create();
```

**Comment by cleandevcode** [comment] 2023-02-07 11:46
Thanks for your message.

I call this `connectUser` when app is initializing.
Btw for some reason, channel might be created without calling `connectUser` due to my codebase.

My question is:
1. Will be any option to check if `connectUser` is called or not.
2. Any specif disconnect user is needed?

Best

**Comment by vanGalilea** [comment] 2023-03-08 09:54
> Btw for some reason, the channel might be created without calling `connectUser` due to my codebase.

@cleandevcode, thanks for your response. 
This should not happens ("the channel might be created without calling `connectUser`"), please revisit your implementation.

I'll be closing this issue and also suggest you having a similar [check/fail mechanism](https://github.com/GetStream/stream-chat-js/blob/b607bd7075249ad69cd42ed956de9acee9113589/src/client.ts#L1743):
`if (!this.userID && !this._isUsingServerAuth()) {}` before channel creation.

**Closed by vanGalilea** 2023-03-08 09:54 UTC
