### ISSUE TITLE
Guard from watching a channel while already watched

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-js#1107] opened 2023-03-21 16:59 UTC
**Describe the bug**
Watching a channel while already watched causes issues. (double replied messages when replied to a deleted message)

**To Reproduce**

- Watch a channel that is already watched.

1. Send a message.
2. Compose a message that replies to the message (from step 1).
3. Delete the message from step 1.
4. retrieve channel messages.
5. replied message (from step 2) will appear twice in that list.

**Expected behavior**
No duplicate messages should appear

**Additional context**
I suggest a warning when calling `channel.watch` when the message is already watched and to make sure we're not rewatching it.

**Comment by rsnay** [comment] 2023-07-03 20:29
Is there currently any flag or indicator of whether a channel is actively being watched?

**Comment by MartinCupela** [comment] 2024-08-28 09:04
@rsnay , you can check, whether your user is watching channel by accessing `channel.state.watchers` object and finding your user there.

**Comment by MartinCupela** [comment] 2024-08-28 09:04
Closing the issue as I could not reproduce it.

**Closed by MartinCupela** 2024-08-28 09:04 UTC
Labels: bug
