### ISSUE TITLE
Webhook event type defs

### ISSUE THREAD

**Issue by Martin-J-Lee** [GetStream/stream-chat-js#696] opened 2021-06-02 07:47 UTC
We are building the chat event consumer.

It would be nice if event definition is somewhere in this module. The following is what I've worked out based on the resource I have so far.
``` typescript
// These types are the best guess from the api doc https://getstream.io/chat/docs/other-rest/webhook_events/
// & observation of actual web hook call as there isn't definite definition on these event types

export type RawChatEvent = {
  type: string;
  created_at: Date;
};

type ChatEventBase = RawChatEvent & {
  cid: string;
};

type ChatMessageEventBase = ChatEventBase & {
  channel_id: string;
  channel_type: string;
  user: User;
  message: ChatMessage;
};

// Chat Message Events
export type ChatMessageNewEvent = ChatMessageEventBase & {
  members?: ChatMembersEntity[];
  watcher_count: number;
};
export type ChatMessageReadEvent = ChatMessageEventBase;
export type ChatMessageUpdatedEvent = ChatMessageEventBase;
export type ChatMessageDeletedEvent = ChatMessageEventBase;
export type ChatMessageFlaggedEvent = ChatMessageEventBase & {
  members?: ChatMembersEntity[];
  channel?: ChatChannel;
  automoderation?: boolean;
  automoderation_scores?: AutomoderationScores;
  Custom?: null;
};
export type ChatMessageUnflaggedEvent = ChatMessageEventBase;

// Chat Reaction Events
export type ChatReactionNewEvent = ChatMessageEventBase & {
  reaction: LatestReactionsEntity;
};
export type ChatReactionDeletedEvent = ChatReactionNewEvent;

// Chat Member Events
export type ChatMemberAddedEvent = ChatEventBase & {
  member: ChatMembersEntity;
  user: User;
};
export type ChatMemberUpdatedEvent = ChatMemberAddedEvent;
export type ChatMemberRemovedEvent = ChatEventBase & {
  user: User;
};

// Chat Channel Events
export type ChatChannelUpdatedEvent = ChatEventBase & {
  channel: ChatChannel;
};
export type ChatChannelDeletedEvent = ChatChannelUpdatedEvent;

// Chat User Events
type ChatUserBase = RawChatEvent & {
  user: User;
};
export type ChatUserBannedEvent = ChatUserBase & {
  reason: string;
  created_by: User;
  expiration: Date;
};
export type ChatUserDeactivatedEvent = ChatUserBase & {
  created_by_id: string;
};
export type ChatUserDeletedEvent = ChatUserBase;
export type ChatUserReactivatedEvent = ChatUserDeactivatedEvent;
export type ChatUserUnbannedEvent = ChatUserBase;
export type ChatUserUpdatedEvent = ChatUserBase & {
  members: User[];
};

export type ChatMessage = {
  id: string;
  text: string;
  html: string;
  type: string;
  user: User;
  attachments?: any[];
  latest_reactions?: LatestReactionsEntity[];
  own_reactions?: any[];
  reaction_counts?: ChatReactions;
  reaction_scores?: ChatReactions;
  reply_count: number;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date;
  mentioned_users?: User[];
  shadowed?: boolean;
  silent?: boolean;
  pinned?: boolean;
  pinned_at?: Date;
  pinned_by?: null;
  pin_expires?: null;
};

export type ChatReactions = { love: number };

export type User = {
  id: string;
  role: string;
  created_at: Date;
  updated_at: Date;
  last_active: Date;
  banned: boolean;
  online: boolean;
  name: string;
  channel_unread_count?: number;
  channel_last_read_at?: Date;
  total_unread_count?: number;
  unread_channels?: number;
  unread_count?: number;
};

export type ChatMembersEntity = {
  user_id: string;
  user?: User[];
  created_at: Date;
  updated_at: Date;
};

export type LatestReactionsEntity = {
  message_id: string;
  user_id: string;
  user: User;
  type: string;
  score: number;
  created_at: Date;
  updated_at: Date;
};

export type ChatChannel = {
  id: string;
  type: string;
  cid: string;
  last_message_at: Date;
  created_at: Date;
  updated_at: Date;
  created_by?: User;
  frozen: boolean;
  config?: Config;
  hide_messages_before: string;
  Custom?: null;
};

export type AutomoderationScores = {
  toxic: number;
  severe_toxic: number;
  obscene: number;
  threat: number;
  insult: number;
  identity_hate: number;
  fine: number;
  spam: number;
  ham: number;
};

export type Config = {
  created_at: string;
  updated_at: string;
  name: string;
  typing_events: boolean;
  read_events: boolean;
  connect_events: boolean;
  search: boolean;
  reactions: boolean;
  replies: boolean;
  mutes: boolean;
  message_retention: string;
  max_message_length: number;
  automod: string;
  commands?: string[];
};

```

gz#12383

**Comment by nhannah** [comment] 2021-07-14 19:37
Duplicate of #682

**Closed by nhannah** 2021-07-14 19:37 UTC
