### ISSUE TITLE
Update Avatar for User in Chat

### ISSUE THREAD

**Issue by danish-gahlout** [GetStream/stream-chat-js#217] opened 2020-01-07 11:18 UTC
Hi Team,
Trying to update the Chat Avatar (As per below given snapshot) for the User once he will select to upload a new image from the Upload button we have in our application.
To achieve this I have tried some in built functions (client.setUser & client.partialUpdateUser) given in the GetStream documentation to update the image for that particular user but it didn’t updated.
Please suggest what is the best way to achieve this.

![image](https://user-images.githubusercontent.com/19967779/71891751-46f6d800-316d-11ea-88fd-b3690322dab5.png)

**Comment by jaapbakker88** [comment] 2020-01-07 14:13
@danish-gahlout can you share how you used the client.setUser and client.partialUpdateUser?

Can you double check if you do it the way we do it in our tests? 
https://github.com/GetStream/stream-chat-js/blob/aef897a0fb175f0ad35e465ccf7a59d4085fc373/test/test.js#L768

**Comment by danish-gahlout** [comment] 2020-01-08 08:07
Hi @jaapbakker88 ,
I have tried in below given way -

`await chatClient.disconnect()
    await chatClient.setUser(
        {
            id: Id,
            name: userName,
            image: avatar,
        },
        token,
    )`

`const update = {
        id: Id,
        set: {
            field: {
                name: preferredName,
                image: avatar,
            },
        },
    }
    await chatClient.partialUpdateUser(update)`

But neither image not name is updating.

In our case user already have a name and avatar image, he has an option to upload the new image and can change the name as well.

**Comment by danish-gahlout** [comment] 2020-01-08 10:01
Hi @jaapbakker88 ,
Please have a look on below snapshot, we need to change these two fields -

![image](https://user-images.githubusercontent.com/19967779/71968941-c814a480-322b-11ea-8a44-3c7a3a274604.png)

**Comment by jaapbakker88** [comment] 2020-01-09 10:05
@danish-gahlout you got me confused for a second and I admit the docs are not very clear on this. Because the fields key, is a custom field itself you're setting. So to get the result you want you want to run it like this:  
```
const update = { 
    id: Id, 
    set: { 
        name: preferredName, 
        image: avatar, 
    }, 
} 
await chatClient.partialUpdateUser(update)
```

**Comment by danish-gahlout** [comment] 2020-01-09 10:31
Hi @jaapbakker88 ,
Thanks for updating, I also tried with updateUser yesterday it was updating the name, now i tried with partialUpdateUser which you gave in last comment, it's also updating the same.

But the problem with both the functions is - that avatar is not updating after uploading the image, but once we do a chat message or page refresh then it got updated.

**Comment by danish-gahlout** [comment] 2020-01-09 10:45
@jaapbakker88 Can we have a 5 minutes of call on Slack/Lync or anywhere which is possible for you. So i can show you the current behavior.

**Comment by jaapbakker88** [comment] 2020-01-09 10:46
Sure, send me a link

**Comment by danish-gahlout** [comment] 2020-01-09 10:58
Can you please join on below link -

https://zoom.us/j/3837226107

**Comment by jaapbakker88** [comment] 2020-01-09 11:50
Sorry, I'm booked with meetings the rest of this day. But I think I know what the problem is. Right now we don't support the behaviour you're looking at, so we're not saving the user in the local state but we get it on every new message as the attached user. I will add it to the backlog though.

**Comment by danish-gahlout** [comment] 2020-01-09 11:52
Okay..
Thanks @jaapbakker88 for the support.

**Comment by jaapbakker88** [comment] 2020-01-10 09:40
I'm going to close this issue and will add the auto updating of user details to the backlog.

**Closed by jaapbakker88** 2020-01-10 09:40 UTC
