### ISSUE TITLE
User still can send messages to the frozen channel

### ISSUE THREAD

**Issue by carishkaa** [GetStream/stream-chat-js#1017] opened 2022-07-21 11:16 UTC
👋🏼 Hi, 

I tried to [freeze channel](https://getstream.io/chat/docs/node/disabling_channels/?language=javascript#freeze-a-channel) with 
```
await channel.update(
  { frozen: true },
  { text: 'Channel is frozen now', user_id: id }
)
```
then send message (UPD: I tried to send messages both on client side, but it didn't work so I tried it on serverside too)
```
await channel.sendMessage({
  text: 'Try to send message to frozen channel',
  user_id: id,
})
```
and it doesn't give me any error.
I haven't set any special permissions for these users, but I can still send messages to the frozen channel, where could the problem be?
The version of GetStream I use: `"stream-chat": "^6.5.1"`, Node.js.

<img  alt="Chat Screen" src="https://user-images.githubusercontent.com/74790419/180190599-ab98c1e3-0885-4df1-9541-7ab93fdd7af5.jpg" width="400">
<img width="244" alt="Chat Explorer" src="https://user-images.githubusercontent.com/74790419/180193675-d8fdd769-3187-436a-8b5a-d2892b5da215.png">

**Comment by carishkaa** [comment] 2022-07-22 09:22
I tried to workaround it with 
```
await channel.updatePartial({
  set: {
    config_overrides: {
      grants: {
        user: ["!create-message"],
      },
    },
  },
})
```
but it didn't work as well. On the other hand disabling the channel works fine, but it's not what I need.

**Comment by ffenix113** [comment] 2022-07-22 12:02
Hello, thank you for posting an issue.

In the provided example there is `user_id` present for both requests, which seems like using a serverside client for these requests. If this is correct - then it is expected behavior, as such clients do no permission checks. Please see a warning here: https://getstream.io/chat/docs/rest/#server_side

**Comment by carishkaa** [comment] 2022-07-22 13:37
Hello, thanks for answering.

Yes, I tried to freeze the channel on the server side, but these messages from screen were sent from the client side. Allow me to describe generally what I am trying to do, I may be misunderstanding what a frozen channel is:

My goal is to deactivate a user on the server side and forbid sending messages from another users to the deactivated ones on the client side. I thought that freezing channels (on server side with `user_id`= id of the user that will be deactivated) match my needs perfectly, but maybe I need to use another functions for this case?

**Comment by miagilepner** [comment] 2022-08-19 10:23
Hi @carishkaa, your staging app has permission checks disabled which would cause this behavior. Please try updating your app and setting `disable_permissions_checks: false`. 

I'm going to close this ticket since this is not related to the JS SDK. If you continue to have problems, please feel free to open up a ticket with our support team.

**Closed by miagilepner** 2022-08-19 10:23 UTC

**Comment by luvishq** [comment] 2022-12-27 18:44
@miagilepner : I don't see this in the app permission, where do we have to disable this check ?
