### ISSUE TITLE
updateUser does not update client.user

### ISSUE THREAD

**Issue by earthlingstd** [GetStream/stream-chat-js#122] opened 2019-09-19 02:03 UTC
I update user profile picture using the following snippet, but the updated info does not reflect in client.user
```
export async function updateUser(user) {
  // if (chatClient.user)
  const res = await chatClient.updateUser({
    id: user.uid,
    name: user.displayName,
    image: user.photoURL,
  })
}
```

**Comment by vishalnarkhede** [comment] 2019-10-04 12:10
Duplicate of https://github.com/GetStream/stream-chat-js/issues/133 . Its in progress :)

**Comment by vishalnarkhede** [comment] 2019-10-17 08:24
Hey @earthlingstd ,

This issue has been fixed. Once the user receives `user.updated` event, you will see the updated information in client.user object.

**Comment by vishalnarkhede** [comment] 2019-11-05 10:20
Closing this issue now!! Please reopen if its not working for you!

**Closed by vishalnarkhede** 2019-11-05 10:20 UTC
Labels: duplicate
