### ISSUE TITLE
Getstream Chat Error: AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by AleenaJoseph426** [GetStream/stream-chat-js#380] opened 2020-07-16 05:50 UTC
I am working with Getstream chat SDk in react native, 
My package.json file looks like: 
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.4",
    **"react": "16.13.1",
    "react-native": "0.63.1",**
    "react-native-device-info": "^5.6.2",
    "react-native-document-picker": "^3.5.3",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.2",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    **"react-navigation": "4.1.0",
    "react-navigation-stack": "^2.8.2",
    "stream-chat-react-native": "^0.13.1"**
  },
I am using the same react native code in the "native message example" provided in the link : https://github.com/GetStream/stream-chat-react-native

While running, The chat list screen is presenting , but on selecting a chat it shows an error as: 
![Simulator Screen Shot - iPhone 11 - 2020-07-16 at 11 01 00](https://user-images.githubusercontent.com/68363600/87630822-a6a0f200-c753-11ea-9646-9100e3a0fe59.png)

Do anyone has the same issue, Could you please help me to solve this.
Thanks in advance.

gz#4468

**Comment by shodgetts** [comment] 2020-07-16 09:09
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4468'>Zendesk ticket #4468</a>:<br><br>Hi,

Thanks for getting in touch.
I'm transferring this to one of our React Native developers for further investigation.
He'll get back to you shortly.

Best regards,
Seni

**Comment by vishalnarkhede** [comment] 2020-07-16 10:33
Duplicate of https://github.com/GetStream/stream-chat-react-native/issues/240

**Closed by vishalnarkhede** 2020-07-16 10:33 UTC
